src/YOGServer.cpp

I did this years ago and don't remember why.
Probably to save some CPU time.

Increase delay between two pools of the server socket.

---

src/AICastor.cpp

memset is called to filll a int array of size 1024 but the third parameter (`n`) is in bytes, so I changed the third argument to multiply by `sizeof(*oldEnough)` which will tell memset the total size of the array. I could've used `sizeof(int)` but then the type would need to be changed in two places if the type of the array changed.
Compiler warning:
```
src/AICastor.cpp: In member function 'bool AICastor::enoughFreeWorkers()':
src/AICastor.cpp:1820:28: warning: 'memset' used with length equal to number of elements without multiplication by element size [-Wmemset-elt-size]
memset(oldEnough, 2, 1024);
^
```

Fix for memset warning.

---

src/AICastor.cpp
src/Map.cpp
src/Map.h
src/Ressource.h

This PR updates `Map::cases` to modern C++, using `std::vector` for storage and (const) reference when accessing it. The changes are not pedantic for using the cleanest modern patterns, but rather pragmatic to improve code readability, maintainability and type safety while having somewhat minimal changes at that point.
Any wants to review and comments and this new style is welcome.

Cleaned-up Map::cases.

---

src/VoiceRecorder.cpp

Fixes:
* a crash when exiting the game if compiled with PortAudio support and `Pa_OpenDefaultStream()` fails with the error "Device unavailable". When this happens, the stream pointer is not initialized (wild pointer) and then the game crashes in `Pa_CloseStream()`.
* a memory leak (#43). Easily fixed by changing `speex_bits_reset` to `speex_bits_destroy` in the destructor.
* a compilation warning and error.

Voicerecorder bug fixes

---

libgag/src/GraphicContext.cpp

In GraphicContext::printScreen, when OpenGL support is compiled in and enabled and the Print Screen key is pressed, `toPrint` variable goes out of scope but `toPrintSurface` still points to its `sdlsurface` member when calling `SDL_SaveBMP()`. When `toPrint` goes out of scope, it is destroyed and its destructor frees sdlsurface, and then toPrintSurface points to an invalid surface. The game then crashes in SDL_SaveBMP because an invalid surface is passed to SDL_SaveBMP().
I changed it from a stack allocated variable to a dynamically allocated variable in the enclosing scope; this seems to fix the bug.
Fixes #47.

Fix crash when pressing Print Screen key on Linux.

---

libgag/src/GUIBase.cpp
libgag/src/GUIMessageBox.cpp
src/FertilityCalculatorDialog.cpp
src/GameGUI.cpp
src/MapEdit.cpp
src/YOGClientGameConnectionDialog.cpp

This was overlooked in the transition from SDL 1.2 to 2.
> SDLMod is now SDL_Keymod and its "META" keys (the "Windows" keys) are now called the "GUI" keys.
-- https://wiki.libsdl.org/MigrationGuide

Fix handling of quit shortcut keys in SDL2.

---

data/glob2.desktop

I am currently packaging your game for @openSUSE and ran into this error that every distribution seems to patch on their own:
```
invalid-desktopfile /usr/share/applications/glob2.desktop key "GenericName[en_US]" in group "Desktop Entry" is a localized key, but there is no non-localized key "GenericName"
[   56s] .desktop file is not valid, check with desktop-file-validate
```

Polished the .desktop file

---

libgag/src/win32_dirent.cpp

Globulation 2 master~9 (214dfb22) was crashing in ntdll!RtlEnterCriticalSection on MSys2 environment in Windows 10 because the handle passed to readdir was the wrong type. Windows doesn't have a native readdir function, so Glob2 implements it using _findnext64i32. _findnext64i32 expects the handle to be of type intptr_t but it was long instead.
I thought I made a pull request for this fix before but I had pushed the commit but forgot to make a pull request for it.
The type of _findnext64i32 is as follows:
```c++
int _findnext64i32(
intptr_t handle,
struct _finddata64i32_t *fileinfo
);
```
To reproduce:
1. Compile Globulation 2 in MSys2.
2. Start Globulation2
3. Click Load Game on main menu.
Actual results:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffd9279faad in …
```

Fix crash in readdir emulation on Windows MSys2.

---

SConstruct

scons was failing if it couldn't find SDL1.2 libraries even
when SDL2 libraries were available. Since Globulation 2 uses SDL2 now,
require SDL2 libraries to remove the dependency on SDL1.2.

Check for SDL2 versions of SDL libraries.

---

libgag/src/KeyPress.cpp

SDL_GetKeyName gives "Return" for the Enter key.
The string "Return" wasn't found in the string table because doesStringExist
does a case-sensitive search for the string and it starts with an uppercase
character, but the string in the string table is all lowercase. Since it
was not found, KeyPress defaults to using the char value of the keysym,
which is '\r'. There isn't an '\r' in the KeyboardManager's list of
shortcuts, so getAction returns DoNothing and the chat box never appears.
This commit also fixes Escape key not opening menu and the Pause button
doing nothing.

Fix Enter key not opening chat text input box.

---

src/MapGenerator.cpp

The Boost header math/common_factor.hpp is deprecated, so use
integer/common_factor.hpp instead.
Fixes #68.

Use common_factor.hpp from integer instead of math.

---

src/AIWarrush.cpp

This pull request tries to correct a confusing if statement in the Warrush AI. I think the if statement tries to check for a building of the same type and number of workers as the parameters given to the method, and either under construction or requires workers (e.g. swarm, inn). The five types of buildings it checks against don't need workers to gather resources for them.
Fixes #70.

Fix confusing if statement in AIWarrush.cpp

---

libgag/include/CursorManager.h
libusl/src/code.h
libusl/src/interpreter.cpp
libusl/src/lexer.h
libusl/src/token.cpp
libusl/src/token.h
libusl/src/types.h
src/AICastor.h
src/BitArray.cpp
src/Brush.h
src/GameGUIMessageManager.h
src/Sector.h
src/SoundMixer.cpp
src/Utilities.cpp
src/VoiceRecorder.cpp

This pull request has some changes that made the code work better with Visual Studio and refactor some code that uses non-standard stuff like private GCC namespaces and `__attribute__`. Also, there is a workaround for microsoft/vcpkg#2292 included.
I'll make a separate pull request for the VS project files.

Windows fixes

---

src/Team.cpp

This pull request fixes an assertion failure under MSVC when upgrading the hospital at the start of tutorial 4. A for loop in Team::syncStep increments the iterator immediately after erasing an element. When the list only has one element, erasing that element and then incrementing causes an assertion failure which says "Cannot increment end list iterator". I spent a few hours yesterday trying to figure out why it crashes but didn't find the solution until I came across [this stackoverflow post](https://stackoverflow.com/questions/16269696/erasing-while-iterating-an-stdlist) today.
There is also a fix for a logic bug included in this PR.
Fixes #74.

Fix Team.cpp assertion fail under MSVC

---

libgag/include/GAGSys.h
libgag/src/TextStream.cpp
src/IRC.h
src/Utilities.cpp

Visual Studio 2015 conforms better to the C standard than previous versions and actually has snprintf without the underscore. snprintf [was added](https://stackoverflow.com/a/8712996/8890345) in Visual Studio 2015. A _MSC_VER macro with a value ≥ 1900 [indicates VS2015 or later](https://github.com/cpredef/predef/blob/master/Compilers.md#microsoft-visual-c).
> Beginning with the UCRT in Visual Studio 2015 and Windows 10, vsnprintf is no longer identical to _vsnprintf. The vsnprintf function conforms to the C99 standard; _vnsprintf is kept for backward compatibility with older Visual Studio code.
> – [`vsnprintf`, `_vsnprintf`, `_vsnprintf_l`, `_vsnwprintf`, `_vsnwprintf_l`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprint …

Avoid defining snprintf & friends on VS2015+.

---

src/AICastor.cpp
src/Sector.cpp
src/Team.cpp

Here's some more fixes for iterators. See issue #74 and PR #75 for an explanation. I think the assertion failure only happens in debug builds when building with Visual Studio's `cl.exe`, but it *might* be undefined behavior to attempt to increment an iterator that is pointing at the end, so it could cause problems in release builds too. I don't know for sure because I haven't read the C++ draft or bought a copy of C++ standard document. [Is it allowed to increment an end iterator?](https://stackoverflow.com/a/39820063/8890345) says it's undefined.

More iterator fixes

---

libgag/src/GUIFileList.cpp
src/EndGameScreen.cpp
src/MapHeader.cpp

These classes were deprecated in C++11 and removed in C++17.
Fixes #55.

Remove uses of {bi,u}nary_function warned by GCC12.

---

.gitignore
glob2.vcxproj
libgag/src/GraphicContext.cpp
src/VoiceRecorder.cpp

This pull request does the following:
* replaces the variable length arrays (VLAs) in Globulation 2 with `valarray`s to make it compile on Visual Studio.
* Ignores the headers downloaded by `vcpkg` during compilation. This reduces the total changes listed in Git Changes by 90% from 8983 changes to 838 changes. The rest of the changes are Visual Studio / VSCode settings or my various build directories. 
* Enables multi-core compilation in Visual Studio.

More msvc improvements

---

src/Engine.cpp
src/GameHeader.cpp
src/GlobalContainer.cpp
src/MapHeader.cpp

This PR fixes crashes found when fuzzing Globulation 2 [beta4.5-571-gd9e683c8](https://github.com/Globulation2/glob2/commit/d9e683c822e2a66b41968200129c1e9b0534bfa0) in headless mode with [AFL++ 4.07a](https://github.com/AFLplusplus/AFLplusplus) on an openSUSE 15.5 VirtualBox VM.
Fuzzed with `AFL_MAP_SIZE=2097152 afl-fuzz -i input -o output -f testcase.game -- build/src/glob2 -nox testcase.game 1 1` using an Auto_save.game file I happened to have lying around.
Each testcase can be checked with `gdb --ex run --args build/src/glob2 -nox <save file name> 1 1`. Note that, at least in Bash, the colons in the filename need to be escaped with backslashes.
[crashingsaves.zip](https://github.com/Globulation2/glob2/files/11717251/crashingsaves.zip) …

Fix headless segfaults when loading corrupted save games

---

libusl/src/types.cpp
libusl/src/types.h
libusl/src/usl.cpp
libusl/src/usl.h

Fixes issue #43.
Note: Rule of Three copy (assignment) operators are not included with this commit.

Fix USL memory leak.

---

libgag/include/SDLCompat.h
libgag/include/SDLGraphicContext.h
libgag/src/GUIBase.cpp
libgag/src/GUIMessageBox.cpp
src/EndGameScreen.cpp
src/Engine.cpp
src/Engine.h
src/FertilityCalculatorDialog.cpp
src/Game.cpp
src/GameGUIMessageManager.cpp
src/GameGUIMessageManager.h
src/MapEdit.cpp
src/NetBroadcastListener.cpp
src/NetBroadcastListener.h
src/NetBroadcaster.cpp
src/NetBroadcaster.h
src/NetConnectionThread.cpp
src/ScriptEditorScreen.cpp
src/YOGClientGameConnectionDialog.cpp
src/YOGServer.cpp
src/YOGServer.h
src/YOGServerGame.cpp
src/YOGServerGame.h
src/YOGServerPlayer.cpp
src/YOGServerPlayer.h
src/YOGServerRouter.cpp

As explained in #80, SDL_GetTicks will overflow to 0 after about 49 days, because it uses a 32-bit unsigned type to store milliseconds rather than a 64-bit type. This PR fixes that and also changes the assigned variables to be 64-bit.
Put compatibility shim in place for SDL < 2.0.18.
Fixes #80.

Fix the 49 days overflow problem.

---

debian/patches/03_headers_order.patch

In PR #78, "snprintf & friends", I changed an #ifdef near the line that was moved in [patch `#3`](https://github.com/Globulation2/glob2/blob/d9e683c822e2a66b41968200129c1e9b0534bfa0/debian/patches/03_headers_order.patch). That change fixes an error with Visual Studio 2015 and later, but caused the patch to fail to apply in GitHub Actions PR #77.
Edit: Oops, I meant PR #78, not `#96`.

Fix patch 03_headers_order.

---

src/Version.h
src/YOGServer.cpp

Differences between v27 and v28 should not affect the metaserver
Resolves #116

YOGServer: Allow client version 27

---

libusl/src/code.cpp
libusl/src/native.h
libusl/src/types.cpp
libusl/src/types.h
libusl/src/usl.cpp
libusl/src/usl.h
src/MapScriptUSL.cpp

Uses unique_ptrs for the root and root->prototype, but the rest is garbage collected.
The problem was that two Scopes had each other as a local, so deleting
locals in the Scope destructor caused one of them to be deleted twice.

Fix libUSL crash due to a circular reference
